# <span style="color:red; font-size: 30px"> Assignment 9 - Due Thursday, April 16th at 8am ET</span>

<font size = "3">

This is a graded homework assignment - no part may be used within a prompt to an LLM

Complete the code cells in this Jupyter notebook, and submit the final .ipynb notebook to Gradescope.

**Please do the following in VS code before you submit**:

- Click "Clear All Outputs"

- Click "Restart"

- Run all code cells

- Save the file

**Note:** Output should match the code that appears in its corresponding cell.

<font size = "3">

Import the familiar libraries ``pandas`` and ``numpy``.

In addition, we'll import a sublibrary from the ``statsmodels`` library. We'll use this in problem (a)

In [1]:
import pandas as pd 
import numpy as np 

# for problem (a)
import statsmodels.formula.api as smf

<font size = "4">

**(a) Linear Regression**

<font size = "3">

Read in the F1 data from "results.csv" in the data folder, assigning it to a DataFrame. For F1 races, we might guess that there is a simple linear relationship between the number of points scored by a driver ("points"), the number of laps completed by the driver ("laps"), and the driver's starting position ("grid"). In particular, a better starting position and a larger number of completed laps should lead to a higher number of points.

In particular, we expect that these three variables are related by the approximate equality:

$$ p_i \approx a\cdot \ell_i + b\cdot g_i + c$$

where:

- $i$ is the index of the result (row $i$ of the DataFrame)
- $p_i$ is the number of points scored in result $i$
- $\ell_i$ is the number of laps completed in result $i$
- $g_i$ is the starting "grid" position of result $i$.
- $a$, $b$, and $c$ are the the coefficients of the linear model we need to determine.

In this model, we say that "laps" and "grid" are both **independent variables** and "points" is the **dependent variable**.

- Use ``smf.ols`` (Ordinary Least Squares) to compute the 3 coefficients of the model by running the following line of code (the names "dependent_var/independent_var1/independent_var2" are placeholder names - substitute the appropriate column names from ``df_results``):
```python
model = smf.ols(formula = "dependent_var ~ independent_var1  + independent_var2", data = df_results)
```

- Compute a Pandas ``Series`` containing the computed coefficients $a$, $b$, and $c$ from the linear model. You can do this as follows:
```python
        coeffs = model.fit().params
```
- Assign the entries of ``coeffs`` to 3 floating-point variables ``a``, ``b``, ``c`` corresponding to the coefficients of the model.

- Define two variables ``grid_val = 3`` and ``laps_val = 55``, which represent the position (grid) and completed laps, respectively, for a given driver. Using these values and the model coefficients, calculate how many points the linear model predicts for this driver, assigning it to the variable ``predicted_points``

In [2]:
df = pd.read_csv("data/results.csv")

model = smf.ols(formula = "points ~ laps + grid", data = df)

coeffs = model.fit().params

print(coeffs)

a = coeffs['Intercept']
b = coeffs['laps']
c = coeffs['grid']


grid_val = 3
laps_val = 55

predicted_points = a * laps_val  + b * grid_val + c
print(predicted_points)

Intercept    2.548916
laps         0.039012
grid        -0.222258
dtype: float64
140.085163670518

<font size = "4">

**(b) Recoding variables**

<font size = "3">

- Read in the file "players_15.csv" from the "data" folder and assign it to a DataFrame. (You might get a warning message, which is *not* the same things as an error message)

- The DataFrame has a column called "wage_eur" which records player wages given in Euros.

- Use the function `pandas.cut` to add a new column to the DataFrame called "wage_level" that categorizes wages as follows:

    - 'Low' if $\textrm{wage} \leq 50,000$

    - 'Medium' if $50,000 < \textrm{wage} \leq 100,000$

    - 'High' if $100,000 < \textrm{wage} \leq 200,000$

    - 'Elite' if $200,000 < \textrm{wage}$

In [3]:
df = pd.read_csv("data/players_15.csv")

lat_labels = ["Low", "Medium", "High", "Elite"]
bins = [-np.inf, 50000, 100000,200000, np.inf]

df["wage_level"] = pd.cut(df["wage_eur"], 
                                bins = bins,
                                right = True,
                                labels = lat_labels)

print(df.head())
print(df["wage_level"])
df.describe()

   sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...
2       9014  https://sofifa.com/player/9014/arjen-robben/15...
3      41236  https://sofifa.com/player/41236/zlatan-ibrahim...
4     167495  https://sofifa.com/player/167495/manuel-neuer/...

          short_name                            long_name player_positions  \
0           L. Messi       Lionel Andrés Messi Cuccittini               CF
1  Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro           LW, LM
2          A. Robben                         Arjen Robben       RM, LM, RW
3     Z. Ibrahimović                   Zlatan Ibrahimović               ST
4           M. Neuer                   Manuel Peter Neuer               GK

   overall  potential    value_eur  wage_eur  age  ...    cb   rcb    rb  \
0       93         95  100500000.0  550000.0   27  ...  45+3  45+3  54+3
1       92         92   79000000.0  375000.0   29  ...  52+3  52+3  57+3
2       90         90   54500000.0  275000.0   30  ...  46+3  46+3  55+3
3       90         90   52500000.0  275000.0   32  ...  55+3  55+3  56+3
4       90         90   63500000.0  300000.0   28  ...  38+3  38+3  36+3

     gk                                    player_face_url  \
0  15+3  https://cdn.sofifa.net/players/158/023/15_120.png
1  16+3  https://cdn.sofifa.net/players/020/801/15_120.png
2  14+3  https://cdn.sofifa.net/players/009/014/15_120.png
3  17+3  https://cdn.sofifa.net/players/041/236/15_120.png
4  87+3  https://cdn.sofifa.net/players/167/495/15_120.png

                             club_logo_url  \
0  https://cdn.sofifa.net/teams/241/60.png
1  https://cdn.sofifa.net/teams/243/60.png
2   https://cdn.sofifa.net/teams/21/60.png
3   https://cdn.sofifa.net/teams/73/60.png
4   https://cdn.sofifa.net/teams/21/60.png

                         club_flag_url  \
0  https://cdn.sofifa.net/flags/es.png
1  https://cdn.sofifa.net/flags/es.png
2  https://cdn.sofifa.net/flags/de.png
3  https://cdn.sofifa.net/flags/fr.png
4  https://cdn.sofifa.net/flags/de.png

                              nation_logo_url  \
0    https://cdn.sofifa.net/teams/1369/60.png
1    https://cdn.sofifa.net/teams/1354/60.png
2  https://cdn.sofifa.net/teams/105035/60.png
3    https://cdn.sofifa.net/teams/1363/60.png
4    https://cdn.sofifa.net/teams/1337/60.png

                       nation_flag_url wage_level
0  https://cdn.sofifa.net/flags/ar.png      Elite
1  https://cdn.sofifa.net/flags/pt.png      Elite
2  https://cdn.sofifa.net/flags/nl.png      Elite
3  https://cdn.sofifa.net/flags/se.png      Elite
4  https://cdn.sofifa.net/flags/de.png      Elite

[5 rows x 111 columns]
0        Elite
1        Elite
2        Elite
3        Elite
4        Elite
         ...
16150      Low
16151      Low
16152      Low
16153      Low
16154      Low
Name: wage_level, Length: 16155, dtype: category
Categories (4, object): ['Low' < 'Medium' < 'High' < 'Elite']

/var/folders/v1/t8dkwqy91pj4flg11ntxz1_80000gn/T/ipykernel_90741/2023803021.py:1: DtypeWarning: Columns (104) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("data/players_15.csv")

,sofifa_id,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,league_level,...,mentality_composure,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
count,16155.000000,16155.000000,16155.000000,1.584400e+04,15916.000000,16155.000000,16155.000000,16155.000000,15916.000000,15916.000000,...,0.0,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,16155.000000,1775.000000
mean,189298.540699,63.830393,68.350108,1.081706e+06,13252.513194,24.776230,181.083627,75.474342,39905.174353,1.378424,...,NaN,45.009037,47.656639,45.885918,15.869514,15.511668,15.354875,15.504735,15.998514,43.865915
std,39762.547872,7.169896,6.580610,2.842704e+06,23608.922510,4.625321,6.618974,6.891796,52050.202038,0.736796,...,NaN,17.915206,18.743105,18.145497,17.576799,16.414173,16.010498,16.585081,17.983209,8.484421
min,2.000000,40.000000,40.000000,1.000000e+03,2000.000000,16.000000,155.000000,50.000000,1.000000,1.000000,...,NaN,20.000000,20.000000,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,20.000000
25%,178042.500000,59.000000,64.000000,1.300000e+05,2000.000000,21.000000,176.000000,70.000000,379.000000,1.000000,...,NaN,25.000000,25.000000,25.000000,8.000000,8.000000,8.000000,8.000000,8.000000,39.000000
50%,200844.000000,64.000000,68.000000,3.500000e+05,5000.000000,24.000000,181.000000,75.000000,1843.000000,1.000000,...,NaN,46.000000,52.000000,49.000000,11.000000,11.000000,11.000000,10.000000,10.000000,44.000000
75%,214349.500000,68.000000,73.000000,8.250000e+05,10000.000000,28.000000,186.000000,80.000000,110398.000000,2.000000,...,NaN,61.000000,64.000000,62.000000,13.000000,14.000000,13.000000,13.000000,13.000000,49.000000
max,254664.000000,93.000000,95.000000,1.005000e+08,550000.000000,44.000000,204.000000,110.000000,113147.000000,4.000000,...,NaN,90.000000,91.000000,95.000000,88.000000,87.000000,92.000000,90.000000,90.000000,66.000000

<font size = "4">

**(c) Compute Cost per Rating by Wage Group**

<font size = "3">

- Continue to use the DataFrame you loaded in question (b)

- Create a new column called "cost_per_rating" which is defined as the ratio between the player's wage and the rating captured in the "overall" column:

$$\textrm{cost per rating} = \frac{\textrm{wage in euros}}{\textrm{overall rating}} $$

- Use `.groupby` to create a DataFrameGroupBy object, grouping by the "wage_level" column. (This might also give you a warning message)

- Compute the average "cost_per_rating" for each wage group, and sort the resulting Pandas Series in descending order.

In [4]:
df["cost_per_rating"] = ((df["wage_eur"])/(df["overall"]))
print(df["cost_per_rating"])

avg_per_group = df.groupby(by = "wage_level")["cost_per_rating"].mean().sort_values(ascending=False)

print(avg_per_group)

0        5913.978495
1        4076.086957
2        3055.555556
3        3055.555556
4        3333.333333
            ...
16150      48.780488
16151      48.780488
16152      50.000000
16153      50.000000
16154      50.000000
Name: cost_per_rating, Length: 16155, dtype: float64
wage_level
Elite     2972.550004
High      1676.011798
Medium     963.498497
Low        127.210624
Name: cost_per_rating, dtype: float64

/var/folders/v1/t8dkwqy91pj4flg11ntxz1_80000gn/T/ipykernel_90741/2985592467.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  avg_per_group = df.groupby(by = "wage_level")["cost_per_rating"].mean().sort_values(ascending=False)

<font size = "4">

**(d) Aggregated Statistics**

<font size = "3">

- Read in the file "monthlysalesdata.csv" in the "data" folder, assigning it to a DataFrame.

- Use `.groupby` to group the dataset by the "Category" variable

- Use the `.agg` method to create a DataFrame with the following aggregated statistics:

    1. The total number of units sold in each category (name this column "total_units")

    2. The average revenue for sales in each category (name this column "mean_revenue")

- Print the resulting DataFrame to the screen. Since the number of units is a whole number, and the mean revenue is in terms of money, ensure the printed DataFrame is rounded to two digits.

In [5]:
data = pd.read_csv("data/monthlysalesdata.csv")
data.describe()

data_agg = data.groupby("Category").agg(total_units = ('Units Sold','sum'),
                             mean_revenue =   ('Revenue ($)','mean'))
print(data_agg.round(2))

           total_units  mean_revenue
Category
Audio              280       5316.67
Computing          155      41333.33
Wearables          360      18000.00

<font size = "4">

**(e) Aggregated Statistics with a user-defined function**

<font size = "3">

- Continue to the use the DataFrame created using "monthlysalesdata.csv".

- Use `.groupby` to group the dataset by the "Branch" variable

- Use the `.agg` method to create a DataFrame with the following aggregated statistics:

    1. The total revenue for each branch (name this column "branch_revenue")

    2. The average customer feedback score for each branch (name this column "mean_rating")

    3. The total number of "high" customer ratings, where a high rating is any rating $\geq 4.5$ (name this column "num_hi_ratings"). You will need to use your own custom function for this statistic.

In [6]:
lat_labels = ["High"]
bins = [4.5, np.inf]

data["num_hi_ratings"] = pd.cut(data["Customer Feedback (1-5)"], 
                                bins = bins,
                                right = True,
                                labels = lat_labels)
def highrate (data):
    num_hi = 0
    for val in data:
        if val >= 4.5:
            num_hi = num_hi + 1 
    return num_hi



data = data.groupby("Branch").agg(branch_revenue = ('Revenue ($)','sum'),
                             mean_rating =   ('Customer Feedback (1-5)','mean'),
                             num_hi_ratings = ('Customer Feedback (1-5)', highrate ))

data.describe()

       branch_revenue  mean_rating  num_hi_ratings
count         3.00000     3.000000        3.000000
mean      64650.00000     4.355556        1.333333
std        9009.30075     0.226895        0.577350
min       54500.00000     4.100000        1.000000
25%       61125.00000     4.266667        1.000000
50%       67750.00000     4.433333        1.000000
75%       69725.00000     4.483333        1.500000
max       71700.00000     4.533333        2.000000